apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-v2-pv
  # namespace: beatrixkiddo-v2-database
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
