apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: beatrixkiddo-v2-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:9
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "G6P6Idh"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        - mountPath: /docker-entrypoint-initdb.d
          name: init-scripts
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-v2-pvc
      - name: init-scripts
        configMap:
          name: db-init-configmap
