apiVersion: v1
kind: Service
metadata:
  name: beatrixkiddo-service
  namespace: beatrixkiddo
spec:
  selector:
    app: beatrixkiddo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP 